// window.jQuery = require('jquery') ;
require('angular') ;
require('angular-sanitize') ;
require('angular-aria') ;
require('angular-cookies') ;
require('angular-resource') ;
window._ = require('underscore') ;
require('bootstrap/dist/css/bootstrap.css') ;
require('angular-ui-router') ;
require('angular-ui-bootstrap');